// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/common.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// for nothing to resp
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2a91dc47a7bb4148, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// for common list req
type ListReq struct {
	Page                 int64             `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int64             `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	NextId               string            `protobuf:"bytes,3,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	Filter               map[string]string `protobuf:"bytes,4,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Order                string            `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2a91dc47a7bb4148, []int{1}
}
func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (dst *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(dst, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListReq) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListReq) GetNextId() string {
	if m != nil {
		return m.NextId
	}
	return ""
}

func (m *ListReq) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

// for common list resp
type ListResp struct {
	Total                int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	LastId               string     `protobuf:"bytes,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	DataList             []*any.Any `protobuf:"bytes,3,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2a91dc47a7bb4148, []int{2}
}
func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (dst *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(dst, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResp) GetLastId() string {
	if m != nil {
		return m.LastId
	}
	return ""
}

func (m *ListResp) GetDataList() []*any.Any {
	if m != nil {
		return m.DataList
	}
	return nil
}

// 坐标
type Coordinate struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Altitude             float64  `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinate) Reset()         { *m = Coordinate{} }
func (m *Coordinate) String() string { return proto.CompactTextString(m) }
func (*Coordinate) ProtoMessage()    {}
func (*Coordinate) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2a91dc47a7bb4148, []int{3}
}
func (m *Coordinate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinate.Unmarshal(m, b)
}
func (m *Coordinate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinate.Marshal(b, m, deterministic)
}
func (dst *Coordinate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinate.Merge(dst, src)
}
func (m *Coordinate) XXX_Size() int {
	return xxx_messageInfo_Coordinate.Size(m)
}
func (m *Coordinate) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinate.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinate proto.InternalMessageInfo

func (m *Coordinate) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coordinate) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinate) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

// 地址
type Location struct {
	Province             string   `protobuf:"bytes,1,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	County               string   `protobuf:"bytes,3,opt,name=county,proto3" json:"county,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_2a91dc47a7bb4148, []int{4}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *Location) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.empty")
	proto.RegisterType((*ListReq)(nil), "pb.list_req")
	proto.RegisterMapType((map[string]string)(nil), "pb.list_req.FilterEntry")
	proto.RegisterType((*ListResp)(nil), "pb.list_resp")
	proto.RegisterType((*Coordinate)(nil), "pb.coordinate")
	proto.RegisterType((*Location)(nil), "pb.location")
}

func init() { proto.RegisterFile("pb/common.proto", fileDescriptor_common_2a91dc47a7bb4148) }

var fileDescriptor_common_2a91dc47a7bb4148 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbd, 0x8e, 0xd4, 0x30,
	0x10, 0xc7, 0x95, 0xe4, 0x36, 0x97, 0xcc, 0x15, 0x20, 0xeb, 0x04, 0x61, 0x45, 0xb1, 0x4a, 0xb5,
	0x55, 0x96, 0x8f, 0x06, 0xe8, 0x28, 0x40, 0x3a, 0x89, 0x2a, 0x2f, 0xb0, 0x72, 0x62, 0x6f, 0x64,
	0xe1, 0xd8, 0xc6, 0x99, 0xac, 0x08, 0x0f, 0xc9, 0x33, 0xa1, 0xb1, 0x93, 0xe5, 0xba, 0xf9, 0xcd,
	0xff, 0xef, 0xf1, 0x7c, 0xc0, 0x0b, 0xd7, 0x9d, 0x7a, 0x3b, 0x8e, 0xd6, 0x34, 0xce, 0x5b, 0xb4,
	0x2c, 0x75, 0xdd, 0xfe, 0xcd, 0x60, 0xed, 0xa0, 0xe5, 0x29, 0x64, 0xba, 0xf9, 0x72, 0xe2, 0x66,
	0x89, 0x72, 0x7d, 0x0f, 0x3b, 0x39, 0x3a, 0x5c, 0xea, 0xbf, 0x09, 0x14, 0x5a, 0x4d, 0x78, 0xf6,
	0xf2, 0x17, 0x63, 0x70, 0xe7, 0xf8, 0x20, 0xab, 0xe4, 0x90, 0x1c, 0xb3, 0x36, 0xc4, 0x94, 0x9b,
	0xd4, 0x1f, 0x59, 0xa5, 0x31, 0x47, 0x31, 0x7b, 0x0d, 0xf7, 0x46, 0xfe, 0xc6, 0xb3, 0x12, 0x55,
	0x76, 0x48, 0x8e, 0x65, 0x9b, 0x13, 0x3e, 0x09, 0xf6, 0x0e, 0xf2, 0x8b, 0xd2, 0x28, 0x7d, 0x75,
	0x77, 0xc8, 0x8e, 0x0f, 0x1f, 0xaa, 0xc6, 0x75, 0xcd, 0x56, 0xbe, 0xf9, 0x1e, 0xa4, 0x6f, 0x06,
	0xfd, 0xd2, 0xae, 0x3e, 0xf6, 0x08, 0x3b, 0xeb, 0x85, 0xf4, 0xd5, 0x2e, 0x14, 0x8a, 0xb0, 0xff,
	0x0c, 0x0f, 0xcf, 0xcc, 0xec, 0x25, 0x64, 0x3f, 0xe5, 0x12, 0xda, 0x2a, 0x5b, 0x0a, 0xe9, 0xd9,
	0x95, 0xeb, 0x39, 0xb6, 0x55, 0xb6, 0x11, 0xbe, 0xa4, 0x9f, 0x92, 0x7a, 0x84, 0x72, 0xfd, 0x70,
	0x72, 0x64, 0x43, 0x8b, 0x5c, 0xaf, 0x13, 0x45, 0xa0, 0xf6, 0x35, 0x9f, 0x42, 0xfb, 0xf1, 0x79,
	0x4e, 0xf8, 0x24, 0xd8, 0x7b, 0x28, 0x05, 0x47, 0x7e, 0xa6, 0x02, 0x55, 0x16, 0x26, 0x78, 0x6c,
	0xe2, 0x12, 0x9b, 0x6d, 0x89, 0xcd, 0x57, 0xb3, 0xb4, 0x05, 0xd9, 0x7e, 0xa8, 0x09, 0xeb, 0x0e,
	0xa0, 0xb7, 0xd6, 0x0b, 0x65, 0x38, 0x4a, 0xf6, 0x16, 0x4a, 0x6d, 0xcd, 0xa0, 0x70, 0x16, 0x71,
	0x8b, 0x49, 0xfb, 0x3f, 0xc1, 0xf6, 0x50, 0x68, 0x8e, 0x51, 0x4c, 0x83, 0x78, 0x63, 0xd2, 0xb8,
	0x5e, 0xb5, 0x2c, 0x6a, 0x1b, 0xd7, 0x17, 0x28, 0xb4, 0xed, 0x39, 0x2a, 0x6b, 0xc8, 0xe7, 0xbc,
	0xbd, 0x2a, 0xd3, 0xcb, 0x75, 0x1f, 0x37, 0xa6, 0x53, 0xf5, 0x0a, 0x97, 0x75, 0xa8, 0x10, 0xb3,
	0x57, 0x90, 0xf7, 0x76, 0x36, 0xb8, 0x6c, 0x97, 0x8a, 0x44, 0x5e, 0x2e, 0x04, 0xdd, 0x29, 0x78,
	0x29, 0xee, 0xf2, 0x30, 0xe3, 0xc7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xad, 0x0a, 0x10, 0x9f,
	0x4d, 0x02, 0x00, 0x00,
}
