// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/manager.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Zone struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{0}
}
func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (dst *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(dst, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

type ZoneInfo struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CorpId               string         `protobuf:"bytes,2,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Loc                  *Location      `protobuf:"bytes,4,opt,name=loc,proto3" json:"loc,omitempty"`
	Coord                *Coordinate    `protobuf:"bytes,5,opt,name=coord,proto3" json:"coord,omitempty"`
	BuildingNum          int64          `protobuf:"varint,6,opt,name=building_num,json=buildingNum,proto3" json:"building_num,omitempty"`
	BuildingCount        int64          `protobuf:"varint,7,opt,name=building_count,json=buildingCount,proto3" json:"building_count,omitempty"`
	Area                 int64          `protobuf:"varint,8,opt,name=area,proto3" json:"area,omitempty"`
	Extra                *_struct.Value `protobuf:"bytes,9,opt,name=extra,proto3" json:"extra,omitempty"`
	Status               int32          `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	ModifyBy             string         `protobuf:"bytes,11,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	CreateAt             int64          `protobuf:"varint,12,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64          `protobuf:"varint,13,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ZoneInfo) Reset()         { *m = ZoneInfo{} }
func (m *ZoneInfo) String() string { return proto.CompactTextString(m) }
func (*ZoneInfo) ProtoMessage()    {}
func (*ZoneInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{0, 0}
}
func (m *ZoneInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneInfo.Unmarshal(m, b)
}
func (m *ZoneInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneInfo.Marshal(b, m, deterministic)
}
func (dst *ZoneInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneInfo.Merge(dst, src)
}
func (m *ZoneInfo) XXX_Size() int {
	return xxx_messageInfo_ZoneInfo.Size(m)
}
func (m *ZoneInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneInfo proto.InternalMessageInfo

func (m *ZoneInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ZoneInfo) GetCorpId() string {
	if m != nil {
		return m.CorpId
	}
	return ""
}

func (m *ZoneInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ZoneInfo) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *ZoneInfo) GetCoord() *Coordinate {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *ZoneInfo) GetBuildingNum() int64 {
	if m != nil {
		return m.BuildingNum
	}
	return 0
}

func (m *ZoneInfo) GetBuildingCount() int64 {
	if m != nil {
		return m.BuildingCount
	}
	return 0
}

func (m *ZoneInfo) GetArea() int64 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *ZoneInfo) GetExtra() *_struct.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *ZoneInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ZoneInfo) GetModifyBy() string {
	if m != nil {
		return m.ModifyBy
	}
	return ""
}

func (m *ZoneInfo) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *ZoneInfo) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type ZoneListResp struct {
	Total                int64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	DataList             []*ZoneInfo `protobuf:"bytes,2,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ZoneListResp) Reset()         { *m = ZoneListResp{} }
func (m *ZoneListResp) String() string { return proto.CompactTextString(m) }
func (*ZoneListResp) ProtoMessage()    {}
func (*ZoneListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{0, 1}
}
func (m *ZoneListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneListResp.Unmarshal(m, b)
}
func (m *ZoneListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneListResp.Marshal(b, m, deterministic)
}
func (dst *ZoneListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneListResp.Merge(dst, src)
}
func (m *ZoneListResp) XXX_Size() int {
	return xxx_messageInfo_ZoneListResp.Size(m)
}
func (m *ZoneListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneListResp proto.InternalMessageInfo

func (m *ZoneListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ZoneListResp) GetDataList() []*ZoneInfo {
	if m != nil {
		return m.DataList
	}
	return nil
}

// 建筑
type Building struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Building) Reset()         { *m = Building{} }
func (m *Building) String() string { return proto.CompactTextString(m) }
func (*Building) ProtoMessage()    {}
func (*Building) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{1}
}
func (m *Building) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Building.Unmarshal(m, b)
}
func (m *Building) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Building.Marshal(b, m, deterministic)
}
func (dst *Building) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Building.Merge(dst, src)
}
func (m *Building) XXX_Size() int {
	return xxx_messageInfo_Building.Size(m)
}
func (m *Building) XXX_DiscardUnknown() {
	xxx_messageInfo_Building.DiscardUnknown(m)
}

var xxx_messageInfo_Building proto.InternalMessageInfo

type BuildingInfo struct {
	Id        string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CorpId    string      `protobuf:"bytes,2,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	ZoneId    string      `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Name      string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Loc       *Location   `protobuf:"bytes,5,opt,name=loc,proto3" json:"loc,omitempty"`
	Coord     *Coordinate `protobuf:"bytes,6,opt,name=coord,proto3" json:"coord,omitempty"`
	Models    []string    `protobuf:"bytes,7,rep,name=models,proto3" json:"models,omitempty"`
	ModelUrls []string    `protobuf:"bytes,8,rep,name=model_urls,json=modelUrls,proto3" json:"model_urls,omitempty"`
	// 建筑层数
	LayerNum             int64          `protobuf:"varint,9,opt,name=layer_num,json=layerNum,proto3" json:"layer_num,omitempty"`
	Area                 int64          `protobuf:"varint,10,opt,name=area,proto3" json:"area,omitempty"`
	Extra                *_struct.Value `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`
	Status               int32          `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	ModifyBy             string         `protobuf:"bytes,13,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	CreateAt             int64          `protobuf:"varint,14,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64          `protobuf:"varint,15,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BuildingInfo) Reset()         { *m = BuildingInfo{} }
func (m *BuildingInfo) String() string { return proto.CompactTextString(m) }
func (*BuildingInfo) ProtoMessage()    {}
func (*BuildingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{1, 0}
}
func (m *BuildingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingInfo.Unmarshal(m, b)
}
func (m *BuildingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingInfo.Marshal(b, m, deterministic)
}
func (dst *BuildingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingInfo.Merge(dst, src)
}
func (m *BuildingInfo) XXX_Size() int {
	return xxx_messageInfo_BuildingInfo.Size(m)
}
func (m *BuildingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingInfo proto.InternalMessageInfo

func (m *BuildingInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuildingInfo) GetCorpId() string {
	if m != nil {
		return m.CorpId
	}
	return ""
}

func (m *BuildingInfo) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *BuildingInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuildingInfo) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

func (m *BuildingInfo) GetCoord() *Coordinate {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *BuildingInfo) GetModels() []string {
	if m != nil {
		return m.Models
	}
	return nil
}

func (m *BuildingInfo) GetModelUrls() []string {
	if m != nil {
		return m.ModelUrls
	}
	return nil
}

func (m *BuildingInfo) GetLayerNum() int64 {
	if m != nil {
		return m.LayerNum
	}
	return 0
}

func (m *BuildingInfo) GetArea() int64 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *BuildingInfo) GetExtra() *_struct.Value {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *BuildingInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BuildingInfo) GetModifyBy() string {
	if m != nil {
		return m.ModifyBy
	}
	return ""
}

func (m *BuildingInfo) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *BuildingInfo) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type BuildingListResp struct {
	Total                int64           `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	DataList             []*BuildingInfo `protobuf:"bytes,2,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BuildingListResp) Reset()         { *m = BuildingListResp{} }
func (m *BuildingListResp) String() string { return proto.CompactTextString(m) }
func (*BuildingListResp) ProtoMessage()    {}
func (*BuildingListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{1, 1}
}
func (m *BuildingListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildingListResp.Unmarshal(m, b)
}
func (m *BuildingListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildingListResp.Marshal(b, m, deterministic)
}
func (dst *BuildingListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildingListResp.Merge(dst, src)
}
func (m *BuildingListResp) XXX_Size() int {
	return xxx_messageInfo_BuildingListResp.Size(m)
}
func (m *BuildingListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildingListResp.DiscardUnknown(m)
}

var xxx_messageInfo_BuildingListResp proto.InternalMessageInfo

func (m *BuildingListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BuildingListResp) GetDataList() []*BuildingInfo {
	if m != nil {
		return m.DataList
	}
	return nil
}

type Config struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{2}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

type ConfigInfo struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// corp_id 为空表示全局配置
	CorpId   string `protobuf:"bytes,3,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	Key      string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value    string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Status   int32  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ModifyBy string `protobuf:"bytes,7,opt,name=modify_by,json=modifyBy,proto3" json:"modify_by,omitempty"`
	CreateAt int64  `protobuf:"varint,8,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt int64  `protobuf:"varint,9,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Weight   int64  `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`
	// sub 表示子节点
	Sub                  []*ConfigInfo `protobuf:"bytes,11,rep,name=sub,proto3" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConfigInfo) Reset()         { *m = ConfigInfo{} }
func (m *ConfigInfo) String() string { return proto.CompactTextString(m) }
func (*ConfigInfo) ProtoMessage()    {}
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{2, 0}
}
func (m *ConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigInfo.Unmarshal(m, b)
}
func (m *ConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigInfo.Marshal(b, m, deterministic)
}
func (dst *ConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigInfo.Merge(dst, src)
}
func (m *ConfigInfo) XXX_Size() int {
	return xxx_messageInfo_ConfigInfo.Size(m)
}
func (m *ConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigInfo proto.InternalMessageInfo

func (m *ConfigInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigInfo) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *ConfigInfo) GetCorpId() string {
	if m != nil {
		return m.CorpId
	}
	return ""
}

func (m *ConfigInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConfigInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ConfigInfo) GetModifyBy() string {
	if m != nil {
		return m.ModifyBy
	}
	return ""
}

func (m *ConfigInfo) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *ConfigInfo) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

func (m *ConfigInfo) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *ConfigInfo) GetSub() []*ConfigInfo {
	if m != nil {
		return m.Sub
	}
	return nil
}

type ConfigRetrieveReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MaxDepth             int32    `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRetrieveReq) Reset()         { *m = ConfigRetrieveReq{} }
func (m *ConfigRetrieveReq) String() string { return proto.CompactTextString(m) }
func (*ConfigRetrieveReq) ProtoMessage()    {}
func (*ConfigRetrieveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_manager_80884af306b1d824, []int{2, 1}
}
func (m *ConfigRetrieveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRetrieveReq.Unmarshal(m, b)
}
func (m *ConfigRetrieveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRetrieveReq.Marshal(b, m, deterministic)
}
func (dst *ConfigRetrieveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRetrieveReq.Merge(dst, src)
}
func (m *ConfigRetrieveReq) XXX_Size() int {
	return xxx_messageInfo_ConfigRetrieveReq.Size(m)
}
func (m *ConfigRetrieveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRetrieveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRetrieveReq proto.InternalMessageInfo

func (m *ConfigRetrieveReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigRetrieveReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigRetrieveReq) GetMaxDepth() int32 {
	if m != nil {
		return m.MaxDepth
	}
	return 0
}

func init() {
	proto.RegisterType((*Zone)(nil), "pb.zone")
	proto.RegisterType((*ZoneInfo)(nil), "pb.zone.info")
	proto.RegisterType((*ZoneListResp)(nil), "pb.zone.list_resp")
	proto.RegisterType((*Building)(nil), "pb.building")
	proto.RegisterType((*BuildingInfo)(nil), "pb.building.info")
	proto.RegisterType((*BuildingListResp)(nil), "pb.building.list_resp")
	proto.RegisterType((*Config)(nil), "pb.config")
	proto.RegisterType((*ConfigInfo)(nil), "pb.config.info")
	proto.RegisterType((*ConfigRetrieveReq)(nil), "pb.config.retrieve_req")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerClient is the client API for Manager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerClient interface {
}

type managerClient struct {
	cc *grpc.ClientConn
}

func NewManagerClient(cc *grpc.ClientConn) ManagerClient {
	return &managerClient{cc}
}

// ManagerServer is the server API for Manager service.
type ManagerServer interface {
}

func RegisterManagerServer(s *grpc.Server, srv ManagerServer) {
	s.RegisterService(&_Manager_serviceDesc, srv)
}

var _Manager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Manager",
	HandlerType: (*ManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pb/manager.proto",
}

func init() { proto.RegisterFile("pb/manager.proto", fileDescriptor_manager_80884af306b1d824) }

var fileDescriptor_manager_80884af306b1d824 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdd, 0x6e, 0xd3, 0x3e,
	0x18, 0xc6, 0xd5, 0xa4, 0x49, 0x93, 0xb7, 0x1f, 0xdb, 0xdf, 0xfa, 0x6b, 0xb3, 0x32, 0x40, 0xdd,
	0x04, 0x52, 0x85, 0x50, 0x2a, 0x8d, 0x2b, 0x18, 0x70, 0x32, 0x89, 0x21, 0x11, 0x09, 0x4e, 0x23,
	0x27, 0x71, 0x3b, 0x8b, 0xc4, 0x0e, 0x8e, 0x33, 0x56, 0x8e, 0x91, 0xb8, 0x0b, 0x4e, 0xb9, 0x29,
	0x2e, 0x84, 0x43, 0x64, 0xbb, 0x61, 0x5f, 0xb4, 0xd3, 0xce, 0xfc, 0x3e, 0xcf, 0xab, 0xda, 0x79,
	0x9e, 0x9f, 0x0a, 0xbb, 0x75, 0x36, 0xaf, 0x08, 0x27, 0x4b, 0x2a, 0xe3, 0x5a, 0x0a, 0x25, 0x90,
	0x53, 0x67, 0xd1, 0x4e, 0x9d, 0xcd, 0x73, 0x51, 0x55, 0x82, 0x5b, 0x31, 0x7a, 0xb4, 0x14, 0x62,
	0x59, 0xd2, 0xb9, 0x99, 0xb2, 0x76, 0x31, 0x6f, 0x94, 0x6c, 0x73, 0x65, 0xdd, 0xa3, 0x5f, 0x2e,
	0xf4, 0xbf, 0x0a, 0x4e, 0xa3, 0x6f, 0x2e, 0xf4, 0x19, 0x5f, 0x08, 0x34, 0x01, 0x87, 0x15, 0xb8,
	0x37, 0xed, 0xcd, 0xc2, 0xc4, 0x61, 0x05, 0xda, 0x87, 0x41, 0x2e, 0x64, 0x9d, 0xb2, 0x02, 0x3b,
	0x46, 0xf4, 0xf5, 0x78, 0x5a, 0x20, 0x04, 0x7d, 0x4e, 0x2a, 0x8a, 0x5d, 0xa3, 0x9a, 0x33, 0x7a,
	0x02, 0x6e, 0x29, 0x72, 0xdc, 0x9f, 0xf6, 0x66, 0xc3, 0xe3, 0x51, 0x5c, 0x67, 0x71, 0x29, 0x72,
	0xa2, 0x98, 0xe0, 0x89, 0x36, 0xd0, 0x53, 0xf0, 0x72, 0x21, 0x64, 0x81, 0x3d, 0xb3, 0x31, 0xd1,
	0x1b, 0x46, 0x60, 0x9c, 0x28, 0x9a, 0x58, 0x13, 0x1d, 0xc2, 0x28, 0x6b, 0x59, 0x59, 0x30, 0xbe,
	0x4c, 0x79, 0x5b, 0x61, 0x7f, 0xda, 0x9b, 0xb9, 0xc9, 0xb0, 0xd3, 0xde, 0xb5, 0x15, 0x7a, 0x06,
	0x93, 0xbf, 0x2b, 0xb9, 0x68, 0xb9, 0xc2, 0x03, 0xb3, 0x34, 0xee, 0xd4, 0xd7, 0x5a, 0xd4, 0x6f,
	0x24, 0x92, 0x12, 0x1c, 0x18, 0xd3, 0x9c, 0xd1, 0x0b, 0xf0, 0xe8, 0xa5, 0x92, 0x04, 0x87, 0xe6,
	0x0d, 0x7b, 0xb1, 0x0d, 0x28, 0xee, 0x02, 0x8a, 0x3f, 0x92, 0xb2, 0xa5, 0x89, 0x5d, 0x42, 0x7b,
	0xe0, 0x37, 0x8a, 0xa8, 0xb6, 0xc1, 0x30, 0xed, 0xcd, 0xbc, 0x64, 0x3d, 0xa1, 0x03, 0x08, 0x2b,
	0x51, 0xb0, 0xc5, 0x2a, 0xcd, 0x56, 0x78, 0x68, 0x22, 0x08, 0xac, 0xf0, 0x6a, 0xa5, 0xcd, 0x5c,
	0x52, 0xa2, 0x68, 0x4a, 0x14, 0x1e, 0x99, 0xbb, 0x03, 0x2b, 0x9c, 0x28, 0x6d, 0xb6, 0x75, 0xb1,
	0x36, 0xc7, 0xd6, 0xb4, 0xc2, 0x89, 0x8a, 0xce, 0x20, 0x2c, 0x59, 0xa3, 0x52, 0x49, 0x9b, 0x1a,
	0xfd, 0x0f, 0x9e, 0x12, 0x8a, 0x94, 0xa6, 0x0d, 0x37, 0xb1, 0x03, 0x7a, 0x0e, 0x61, 0x41, 0x14,
	0x49, 0xf5, 0x1e, 0x76, 0xa6, 0xee, 0x6c, 0x78, 0x3c, 0xd6, 0x39, 0xea, 0x1a, 0x63, 0x5d, 0x61,
	0x12, 0x68, 0xff, 0x2d, 0x6b, 0xd4, 0xd1, 0xf7, 0x3e, 0x04, 0x5d, 0x22, 0xd1, 0xcf, 0x07, 0x57,
	0xbc, 0x0f, 0x03, 0xfd, 0xab, 0xda, 0xb0, 0x2d, 0xfb, 0x7a, 0xbc, 0xd6, 0x7d, 0xff, 0x6e, 0xf7,
	0xde, 0xbd, 0xdd, 0xfb, 0xdb, 0xba, 0xdf, 0x03, 0xbf, 0x12, 0x05, 0x2d, 0x1b, 0x3c, 0x98, 0xba,
	0xfa, 0x46, 0x3b, 0xa1, 0xc7, 0x00, 0xe6, 0x94, 0xb6, 0xb2, 0x6c, 0x70, 0x60, 0xbc, 0xd0, 0x28,
	0x1f, 0x64, 0x69, 0xea, 0x28, 0xc9, 0x8a, 0x4a, 0xc3, 0x4b, 0x68, 0x43, 0x35, 0x82, 0x86, 0xa5,
	0xa3, 0x00, 0xfe, 0x45, 0xc1, 0xf0, 0x61, 0x14, 0x8c, 0x36, 0x53, 0x30, 0xde, 0x46, 0xc1, 0x64,
	0x1b, 0x05, 0x3b, 0xb7, 0x28, 0x78, 0x7f, 0x3f, 0x05, 0xf1, 0x5d, 0x0a, 0xfe, 0xd3, 0x89, 0x76,
	0x6d, 0xdf, 0x26, 0xe1, 0xb7, 0x03, 0x7e, 0x2e, 0xf8, 0x82, 0x2d, 0xa3, 0x1f, 0xce, 0x06, 0x0e,
	0x0e, 0x20, 0xac, 0x89, 0xa4, 0x5c, 0x5d, 0x91, 0x10, 0x58, 0xe1, 0xf4, 0x06, 0x24, 0xee, 0x0d,
	0x48, 0x76, 0xc1, 0xfd, 0x44, 0x57, 0x6b, 0x14, 0xf4, 0x51, 0xbf, 0xf8, 0x42, 0xa7, 0x67, 0x58,
	0x08, 0x13, 0x3b, 0x5c, 0xcb, 0xd0, 0xdf, 0x9c, 0xe1, 0x60, 0x5b, 0x86, 0xc1, 0xb6, 0x0c, 0xc3,
	0x9b, 0x19, 0xea, 0xeb, 0xbe, 0x50, 0xb6, 0x3c, 0x57, 0xeb, 0xda, 0xd7, 0x13, 0x3a, 0x04, 0xb7,
	0x69, 0x33, 0x3c, 0x34, 0x91, 0xed, 0x58, 0x08, 0x75, 0x2c, 0x36, 0x30, 0xed, 0x45, 0x67, 0x30,
	0x92, 0x54, 0x49, 0x46, 0x2f, 0x68, 0x2a, 0xe9, 0xe7, 0xee, 0x0b, 0x7b, 0x57, 0x5f, 0x68, 0x93,
	0x73, 0xae, 0x27, 0x57, 0x91, 0xcb, 0xb4, 0xa0, 0xb5, 0x3a, 0x37, 0xf1, 0x78, 0x49, 0x50, 0x91,
	0xcb, 0x37, 0x7a, 0x3e, 0x0e, 0x61, 0x70, 0x66, 0xff, 0xa7, 0x33, 0xdf, 0xe0, 0xf5, 0xf2, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x68, 0xfc, 0x2c, 0xbc, 0x05, 0x00, 0x00,
}
